### ISSUE TITLE
Is extra hamcrest 0.0.0 dependency still necessary?

### ISSUE THREAD

**Issue by SimonScholz** [jsievers/tycho-demo#6]
Hello,

in the pom of the SWT bot project you define an extra dependency to hamcrest 0.0.0, because of JUnit conflicts:

<pre>
&lt;dependencies&gt;
&lt;dependency&gt;
&lt;!-- explicit dependency is only needed because SWTbot brings
its own hamcrest bundle which conflicts with the one from junit in the eclipse
platform --&gt;
&lt;type&gt;p2-installable-unit&lt;/type&gt;
&lt;artifactId&gt;org.hamcrest&lt;/artifactId&gt;
&lt;version&gt;0.0.0&lt;/version&gt;
&lt;/dependency&gt;
&lt;/dependencies&gt;
</pre>

Is this still valid, because in my installation I do  not use this extra depenedency and it works though.
Do you know, if something has been changed concerning this? Maybe on the SWT bot side?

Best regards,

Simon

**Comment by jsievers** [comment]
I don't know

try removing it and see if the test still succeeds
