### ISSUE TITLE
.m2 is missing

### ISSUE THREAD

**Issue by jan2ary** [jsievers/tycho-demo#7]
Hello,

I'm following your demo for creation of tycho build project and I'm stuck at the step "4. Setting up the Tycho build" of the first exercise:
Copy the .m2 folder from the USB stick to your user home directory ~ (Linux/Mac) or %USERPROFILE% (Windows). 
I didn't find a folder named .m2 here. 

Thanks.

**Comment by jsievers** [comment]
the instructions also cover the case where you don't have internet access.
with internet access you can skip this step as maven automatically downloads required artifacts.

**Comment by jsievers** [comment]
BTW in general please ask on tycho-user@eclipse.org or open bugs on bugs.eclipse.org
